apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.appName }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.appName }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      nodePort: {{ .Values.backend.service.nodePort }}

