apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appName }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.appName }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      nodePort: {{ .Values.frontend.service.nodePort }}

